pid logs/sitio2.pid;
events {
	worker_connections 1024;
}
http {
	server {
		listen 82;

		location / {
			root /mnt/c/Users/coppe/Desktop/Desarrollo\ WEB/17349/nginx/3sitios/sitio2;
			index index.html;
		}
	}
}
